enum AlgoType {kKTxx, kANTIKTxx};
enum JetType  {kFULLJETSxx, kCHARGEDJETSxx, kNEUTRALJETSxx};

//________________________________________________________________________________________________
//_____-__________________________________________________________________________________________
AliAnalysisTaskHJetSpectraM* AddTaskHJetSpectra(
  Double_t            jetRadius               = 0.4,  //radius of analyzed jets
  const char*         containerSuffix         = "",   //tag to the name of container in case you run more analyses
  Double_t            trackEtaWindow          = 0.9,   //pseudorapidity range for tracks
  Double_t            acut                    = 0.6,   //cut on relative jet area 0.6 = 60% of pi*R^2
  Int_t               recombscheme            = 5    //recombination scheme  5=BIpt_scheme  0=E_scheme 
){


   if(jetRadius < 0.1) return NULL; // do not analyze jets that are too small

   //Name of MC particles that are generated by AliPythiaGenerator
   TString kTracksNameMC = "MCParticlesSelected"; 

   //Fiducial cut on pseudorapidity of jets (make sure all jets are fully inside ALICE acceptance)
   Double_t jetEtaRange   = TMath::Abs(trackEtaWindow - jetRadius);

   //_________________________________________________________________
   // #### DEFINE MANAGER AND DATA CONTAINER NAMES
   AliAnalysisManager *manager = AliAnalysisManager::GetAnalysisManager();
   if(!manager){
      ::Error("AddTaskHJetSpectra.C", "No analysis manager to connect to.");
      return NULL;
   }
   //_________________________________________________________________
 
   TString containerNameSuffix("");
   if(strcmp(containerSuffix,""))  containerNameSuffix = Form("_%s", containerSuffix);
 
   TString myContName(""); //make unique name of your analysis task
   myContName = Form("AnalysisR%02d_%s", 
      TMath::Nint(jetRadius*10), containerNameSuffix.Data());


   //_________________________________________________________
   //LOAD MACRO FOR  JET FINDER TASKS

   gROOT->LoadMacro("$ALICE_PHYSICS/PWGJE/EMCALJetTasks/macros/AddTaskEmcalJet.C");

   //see this macro to learn what are the parameters of JET FINDER  TASK
   //____________________________________________________________________
   //DEFINE JETS
   AliEmcalJetTask* jetFinderTaskMC = NULL; //ANTIKT JET FINDER
   AliEmcalJetTask* jetFinderRhoKTMC = NULL; //KT JET FINDER
 

      //ANTIKT GENERATOR LEVEL  (specify input particle container name, 
      //                               type of reconstr. algo, jet radius, 
      //                           whether it is charge track jet or full jet 
      jetFinderTaskMC = AddTaskEmcalJet(kTracksNameMC.Data(),"", kANTIKTxx, jetRadius,  kCHARGEDJETSxx,0.150,0.300,0.005,recombscheme, "JetAKTMC",0.,0,0); 
      jetFinderTaskMC->SetMinJetPt(0.150);


      //KT GENERATOR LEVEL
      jetFinderRhoKTMC = AddTaskEmcalJet(kTracksNameMC.Data(),"", kKTxx,   jetRadius, kCHARGEDJETSxx,0.150,0.300,0.005,recombscheme, "JetKTMC",0.,0,0); 
      jetFinderRhoKTMC->SetMinJetPt(0);

 
   //__________________________________________________________________________________
   // #### DEFINE MY ANALYSIS TASK

   TString tname = jetFinderTaskMC->GetName();

   AliAnalysisTaskHJetSpectraM *task = new AliAnalysisTaskHJetSpectraM(
                                      Form("HJetSpectra_%s",tname.Data()));

   task->SetNeedEmcalGeom(kFALSE); 

   //_____________________________________________
   //TRACK/PARTICLE CONTAINTERS  to be attached to my task
   AliParticleContainer *trackContTrue  = 0x0; //mc particles
   trackContTrue = task->AddParticleContainer(kTracksNameMC.Data()); //gen particles   
   trackContTrue->SetClassName("AliVParticle");  
   //_____________________________________________
   //JET CONTAINERS to be attached to my task
   // here you have to futher specify constraints on your jets, e.g. minimum pT
   AliJetContainer *jetContTrue   = 0x0; //jets from mc particles
   AliJetContainer *jetContTrueKT = 0x0; //KT jets from mc particles

   //AKT JET CONTAINERS  GEN   this will be ContainterOne
   jetContTrue = task->AddJetContainer(jetFinderTaskMC->GetName(),"TPC",jetRadius);
   if(jetContTrue){
      jetContTrue->ConnectParticleContainer(trackContTrue);
      jetContTrue->SetPercAreaCut(acut);//0.6
      jetContTrue->SetMinPt(0.15);
      jetContTrue->SetMaxTrackPt(1000);
      jetContTrue->SetJetAcceptanceType(AliJetContainer::kUser);
      jetContTrue->SetJetEtaLimits(-jetEtaRange,jetEtaRange);
   }
   //KT JET CONTAINERS FOR BG GEN this will be  ContainterTwo
   jetContTrueKT = task->AddJetContainer(jetFinderRhoKTMC->GetName(),"TPC",jetRadius);
   if(jetContTrueKT){
      jetContTrueKT->ConnectParticleContainer(trackContTrue);
      jetContTrueKT->SetMinPt(0.);
      jetContTrueKT->SetMaxTrackPt(1000);
      jetContTrueKT->SetJetAcceptanceType(AliJetContainer::kUser);
      jetContTrueKT->SetJetEtaLimits(-jetEtaRange,jetEtaRange);
   }
 
   // #### Task preferences
   task->SetAcceptanceWindows(trackEtaWindow, jetRadius);
 
   task->SetDebugLevel(0); //No debug messages 0

   // output container
   contHistos = manager->CreateContainer(myContName.Data(), TList::Class(), AliAnalysisManager::kOutputContainer, Form("%s:ChJetSpectra%s", AliAnalysisManager::GetCommonFileName(), myContName.Data()));
 
 
   // #### ADD ANALYSIS TASK
   manager->AddTask(task);
   manager->ConnectInput(task, 0, manager->GetCommonInputContainer());
   manager->ConnectOutput(task, 1, contHistos);

   return task;
}
